### PR TITLE
Allow individual retract

### PR DESCRIPTION
**Pull request by ronlawrence3**
This adds buttons to individually retract the belts:

image

### CODE REVIEW

**Comment by ronlawrence3** [comment]
totally optional if you want it. I found it useful. @BarbourSmith

**Comment by BarbourSmith** [comment]
It looks fantastic and I actually used to have buttons for all of those, but I took them out to try to keep things simple. 

I worry that a lot of open source project seem to grow in complexity endlessly because each individual change is good but then collectively there end up being so many features that it gets hard to use. 

I am 200% in support of having multiple options for the index.html.gz file, I don't think that the user interface has to be a once size fits all thing. Would you be interested in posting this in the forums to get feedback from other folks?

I'm kind of envisioning the main one as being the most basic and simple version and then having more advanced versions or things like "dark mode" as options that are out there for folks to download.

**Comment by ronlawrence3** [comment]
I agree with simplifying. I also think there should be a way to get to more advanced things, and this particular point in the process is probably not worth being "front and center" for sure...

Let me take a little more time and design some options for this.  I could have these buttons behind a collapsible "troubleshooting" option so they don't clutter the basic ui (maybe with the test button?), or launch them from the upper right menu or somewhere separate. I'll post something in the forum when I have options to consider. Thanks for the review!

**Comment by BarbourSmith** [comment]
I love both those ideas. I think that hiding them a little bit is a great idea. 

I also do think that we should encourage some alternative and more advanced UIs for folks who want them. I've been thinking it might be cool to visualize the tension in each belt somehow...its useless information that would just confuse 99% of users if we make it the default view, but it would be so cool looking that I think a decent number of folks might find it fun to look at.

**Pull request closed without merging**
