### PR TITLE
Update the input dialog

### PR DESCRIPTION
**Pull request by aersida**
slightly more important than the credits dialog

### CODE REVIEW

**Comment by BarbourSmith** [comment]
This is still bricking the UI for me with `Uncaught SyntaxError: import declarations may only appear at top level of a module` 😞

**Comment by aersida** [comment]
> This is still bricking the UI for me with `Uncaught SyntaxError: import declarations may only appear at top level of a module` 😞

The 'import' problem is not part of this PR. But I do have a separate PR to fix that. See this on
https://github.com/BarbourSmith/ESP3D-WEBUI/pull/75

**Comment by BarbourSmith** [comment]
Awesome!

**Review by BarbourSmith — APPROVED** [review]
👍 👍

**Pull request merged**
