### PR TITLE
Update the Confirm Dialog

### PR DESCRIPTION
**Pull request by aersida**
Update the confirm dialog, used in several places.

### CODE REVIEW

**Review by BarbourSmith — APPROVED** [review]
Excellent 👍 👍

**Comment by BarbourSmith** [comment]
Oops I shoulda tested before merging 😬 

I'm getting `Uncaught SyntaxError: import declarations may only appear at top level of a module` which bricks the UI

**Comment by aersida** [comment]
> Oops I shoulda tested before merging 😬
> 
> I'm getting `Uncaught SyntaxError: import declarations may only appear at top level of a module` which bricks the UI

yeah- I forgot to remove the import/export - now done.

**Comment by BarbourSmith** [comment]
I think you have to make a new PR for me to be able to bring in the change

**Pull request merged**
